const fs = require('fs');
const path = require('path');

const galleryDir = path.join(process.cwd(), 'Gallery');
const galleryDataPath = path.join(process.cwd(), 'JS', 'gallery-data.js');
const imageExtensions = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];

try {
    // 1. Get all subdirectories in the Gallery folder
    const subfolders = fs.readdirSync(galleryDir, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name);

    const galleryItems = [];
    const skippedFolders = [];

    // 2. For each subfolder, find the image and markdown file
    for (const folder of subfolders) {
        const folderPath = path.join(galleryDir, folder);
        const files = fs.readdirSync(folderPath);

        console.log(`\nScanning folder: "${folder}"`);
        console.log(`  Files found: [${files.join(', ')}]`);

        const imageFile = files.find(file => imageExtensions.includes(path.extname(file).toLowerCase()));
        const markdownFile = files.find(file => path.extname(file).toLowerCase() === '.md');

        if (imageFile && markdownFile) {
            console.log(`  SUCCESS: Found image ("${imageFile}") and markdown ("${markdownFile}").`);
            galleryItems.push({
                image: `../Gallery/${folder}/${imageFile}`.replace(/\\/g, '/'),
                markdown: `../Gallery/${folder}/${markdownFile}`.replace(/\\/g, '/')
            });
        } else {
            const reason = !imageFile && !markdownFile ? 'missing image and markdown file' : !imageFile ? 'missing image file' : 'missing markdown file';
            skippedFolders.push({ name: folder, reason: reason });
            console.warn(`[!] Skipping folder "${folder}": ${reason}.`);
        }
    }

    // --- Step 3: Create and write the gallery data file ---
    const galleryItemsString = JSON.stringify(galleryItems, null, 4);
    const fileContent = `// This file is automatically generated by the build script. Do not edit.\nconst galleryItems = ${galleryItemsString};`;

    fs.writeFileSync(galleryDataPath, fileContent, 'utf8');
    const resultMessage = `Build complete. Found ${galleryItems.length} valid item(s). Written to JS/gallery-data.js.`;
    console.log(`\n${resultMessage}`);

} catch (error) {
    console.error('Error building gallery:', error);
}