// This file is automatically generated by the build script. Do not edit.
const galleryItems = [
    {
        "image": "../Gallery/Test/Test.jpg",
        "markdown": "../Gallery/Test/Test.md"
    },
    {
        "image": "../Gallery/01/01.jpg",
        "markdown": "../Gallery/01/01.md"
    }
];